[package]
name = "tobj"
version = "3.2.0"
edition = "2018"
authors = ["Will Usher <will@willusher.io>", "Moritz Moeller <virtualritz@protonmail.com>"]

description = "A lightweight OBJ loader in the spirit of tinyobjloader"
homepage = "https://github.com/Twinklebear/tobj"
documentation = "https://docs.rs/tobj/"
repository = "https://github.com/Twinklebear/tobj"
readme = "README.md"
keywords = ["obj", "wavefront", "graphics"]
license = "MIT"

exclude = [
    "*.obj",
    "*.mtl",
    ".travis.yml",
]

[features]
default = ["ahash"]
merging = []
reordering = []
async = []

[dependencies]
ahash = { version = "0.7.2", optional = true }
log = { version = "0.4.14", optional = true }

[dev-dependencies]
tokio-test = "0.4.2"

[profile.dev]
split-debuginfo = "unpacked"
opt-level = 3

[package.metadata.docs.rs]
 features = ["log", "merging", "reordering", "async"]
